// Copyright (c) 2012 DotNetAnywhere
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

typedef float  (STDCALL *_fC)();
typedef double (STDCALL *_dC)();
typedef U64    (STDCALL *_uC)();
typedef float  (STDCALL *_fCf)(float _0);
typedef float  (STDCALL *_fCd)(double _0);
typedef float  (STDCALL *_fCu)(U32 _0);
typedef double (STDCALL *_dCf)(float _0);
typedef double (STDCALL *_dCd)(double _0);
typedef double (STDCALL *_dCu)(U32 _0);
typedef U64    (STDCALL *_uCf)(float _0);
typedef U64    (STDCALL *_uCd)(double _0);
typedef U64    (STDCALL *_uCu)(U32 _0);
typedef float  (STDCALL *_fCff)(float _0, float _1);
typedef float  (STDCALL *_fCfd)(float _0, double _1);
typedef float  (STDCALL *_fCfu)(float _0, U32 _1);
typedef float  (STDCALL *_fCdf)(double _0, float _1);
typedef float  (STDCALL *_fCdd)(double _0, double _1);
typedef float  (STDCALL *_fCdu)(double _0, U32 _1);
typedef float  (STDCALL *_fCuf)(U32 _0, float _1);
typedef float  (STDCALL *_fCud)(U32 _0, double _1);
typedef float  (STDCALL *_fCuu)(U32 _0, U32 _1);
typedef double (STDCALL *_dCff)(float _0, float _1);
typedef double (STDCALL *_dCfd)(float _0, double _1);
typedef double (STDCALL *_dCfu)(float _0, U32 _1);
typedef double (STDCALL *_dCdf)(double _0, float _1);
typedef double (STDCALL *_dCdd)(double _0, double _1);
typedef double (STDCALL *_dCdu)(double _0, U32 _1);
typedef double (STDCALL *_dCuf)(U32 _0, float _1);
typedef double (STDCALL *_dCud)(U32 _0, double _1);
typedef double (STDCALL *_dCuu)(U32 _0, U32 _1);
typedef U64    (STDCALL *_uCff)(float _0, float _1);
typedef U64    (STDCALL *_uCfd)(float _0, double _1);
typedef U64    (STDCALL *_uCfu)(float _0, U32 _1);
typedef U64    (STDCALL *_uCdf)(double _0, float _1);
typedef U64    (STDCALL *_uCdd)(double _0, double _1);
typedef U64    (STDCALL *_uCdu)(double _0, U32 _1);
typedef U64    (STDCALL *_uCuf)(U32 _0, float _1);
typedef U64    (STDCALL *_uCud)(U32 _0, double _1);
typedef U64    (STDCALL *_uCuu)(U32 _0, U32 _1);
typedef float  (STDCALL *_fCfff)(float _0, float _1, float _2);
typedef float  (STDCALL *_fCffd)(float _0, float _1, double _2);
typedef float  (STDCALL *_fCffu)(float _0, float _1, U32 _2);
typedef float  (STDCALL *_fCfdf)(float _0, double _1, float _2);
typedef float  (STDCALL *_fCfdd)(float _0, double _1, double _2);
typedef float  (STDCALL *_fCfdu)(float _0, double _1, U32 _2);
typedef float  (STDCALL *_fCfuf)(float _0, U32 _1, float _2);
typedef float  (STDCALL *_fCfud)(float _0, U32 _1, double _2);
typedef float  (STDCALL *_fCfuu)(float _0, U32 _1, U32 _2);
typedef float  (STDCALL *_fCdff)(double _0, float _1, float _2);
typedef float  (STDCALL *_fCdfd)(double _0, float _1, double _2);
typedef float  (STDCALL *_fCdfu)(double _0, float _1, U32 _2);
typedef float  (STDCALL *_fCddf)(double _0, double _1, float _2);
typedef float  (STDCALL *_fCddd)(double _0, double _1, double _2);
typedef float  (STDCALL *_fCddu)(double _0, double _1, U32 _2);
typedef float  (STDCALL *_fCduf)(double _0, U32 _1, float _2);
typedef float  (STDCALL *_fCdud)(double _0, U32 _1, double _2);
typedef float  (STDCALL *_fCduu)(double _0, U32 _1, U32 _2);
typedef float  (STDCALL *_fCuff)(U32 _0, float _1, float _2);
typedef float  (STDCALL *_fCufd)(U32 _0, float _1, double _2);
typedef float  (STDCALL *_fCufu)(U32 _0, float _1, U32 _2);
typedef float  (STDCALL *_fCudf)(U32 _0, double _1, float _2);
typedef float  (STDCALL *_fCudd)(U32 _0, double _1, double _2);
typedef float  (STDCALL *_fCudu)(U32 _0, double _1, U32 _2);
typedef float  (STDCALL *_fCuuf)(U32 _0, U32 _1, float _2);
typedef float  (STDCALL *_fCuud)(U32 _0, U32 _1, double _2);
typedef float  (STDCALL *_fCuuu)(U32 _0, U32 _1, U32 _2);
typedef double (STDCALL *_dCfff)(float _0, float _1, float _2);
typedef double (STDCALL *_dCffd)(float _0, float _1, double _2);
typedef double (STDCALL *_dCffu)(float _0, float _1, U32 _2);
typedef double (STDCALL *_dCfdf)(float _0, double _1, float _2);
typedef double (STDCALL *_dCfdd)(float _0, double _1, double _2);
typedef double (STDCALL *_dCfdu)(float _0, double _1, U32 _2);
typedef double (STDCALL *_dCfuf)(float _0, U32 _1, float _2);
typedef double (STDCALL *_dCfud)(float _0, U32 _1, double _2);
typedef double (STDCALL *_dCfuu)(float _0, U32 _1, U32 _2);
typedef double (STDCALL *_dCdff)(double _0, float _1, float _2);
typedef double (STDCALL *_dCdfd)(double _0, float _1, double _2);
typedef double (STDCALL *_dCdfu)(double _0, float _1, U32 _2);
typedef double (STDCALL *_dCddf)(double _0, double _1, float _2);
typedef double (STDCALL *_dCddd)(double _0, double _1, double _2);
typedef double (STDCALL *_dCddu)(double _0, double _1, U32 _2);
typedef double (STDCALL *_dCduf)(double _0, U32 _1, float _2);
typedef double (STDCALL *_dCdud)(double _0, U32 _1, double _2);
typedef double (STDCALL *_dCduu)(double _0, U32 _1, U32 _2);
typedef double (STDCALL *_dCuff)(U32 _0, float _1, float _2);
typedef double (STDCALL *_dCufd)(U32 _0, float _1, double _2);
typedef double (STDCALL *_dCufu)(U32 _0, float _1, U32 _2);
typedef double (STDCALL *_dCudf)(U32 _0, double _1, float _2);
typedef double (STDCALL *_dCudd)(U32 _0, double _1, double _2);
typedef double (STDCALL *_dCudu)(U32 _0, double _1, U32 _2);
typedef double (STDCALL *_dCuuf)(U32 _0, U32 _1, float _2);
typedef double (STDCALL *_dCuud)(U32 _0, U32 _1, double _2);
typedef double (STDCALL *_dCuuu)(U32 _0, U32 _1, U32 _2);
typedef U64    (STDCALL *_uCfff)(float _0, float _1, float _2);
typedef U64    (STDCALL *_uCffd)(float _0, float _1, double _2);
typedef U64    (STDCALL *_uCffu)(float _0, float _1, U32 _2);
typedef U64    (STDCALL *_uCfdf)(float _0, double _1, float _2);
typedef U64    (STDCALL *_uCfdd)(float _0, double _1, double _2);
typedef U64    (STDCALL *_uCfdu)(float _0, double _1, U32 _2);
typedef U64    (STDCALL *_uCfuf)(float _0, U32 _1, float _2);
typedef U64    (STDCALL *_uCfud)(float _0, U32 _1, double _2);
typedef U64    (STDCALL *_uCfuu)(float _0, U32 _1, U32 _2);
typedef U64    (STDCALL *_uCdff)(double _0, float _1, float _2);
typedef U64    (STDCALL *_uCdfd)(double _0, float _1, double _2);
typedef U64    (STDCALL *_uCdfu)(double _0, float _1, U32 _2);
typedef U64    (STDCALL *_uCddf)(double _0, double _1, float _2);
typedef U64    (STDCALL *_uCddd)(double _0, double _1, double _2);
typedef U64    (STDCALL *_uCddu)(double _0, double _1, U32 _2);
typedef U64    (STDCALL *_uCduf)(double _0, U32 _1, float _2);
typedef U64    (STDCALL *_uCdud)(double _0, U32 _1, double _2);
typedef U64    (STDCALL *_uCduu)(double _0, U32 _1, U32 _2);
typedef U64    (STDCALL *_uCuff)(U32 _0, float _1, float _2);
typedef U64    (STDCALL *_uCufd)(U32 _0, float _1, double _2);
typedef U64    (STDCALL *_uCufu)(U32 _0, float _1, U32 _2);
typedef U64    (STDCALL *_uCudf)(U32 _0, double _1, float _2);
typedef U64    (STDCALL *_uCudd)(U32 _0, double _1, double _2);
typedef U64    (STDCALL *_uCudu)(U32 _0, double _1, U32 _2);
typedef U64    (STDCALL *_uCuuf)(U32 _0, U32 _1, float _2);
typedef U64    (STDCALL *_uCuud)(U32 _0, U32 _1, double _2);
typedef U64    (STDCALL *_uCuuu)(U32 _0, U32 _1, U32 _2);
typedef float  (STDCALL *_fCffff)(float _0, float _1, float _2, float _3);
typedef float  (STDCALL *_fCfffd)(float _0, float _1, float _2, double _3);
typedef float  (STDCALL *_fCfffu)(float _0, float _1, float _2, U32 _3);
typedef float  (STDCALL *_fCffdf)(float _0, float _1, double _2, float _3);
typedef float  (STDCALL *_fCffdd)(float _0, float _1, double _2, double _3);
typedef float  (STDCALL *_fCffdu)(float _0, float _1, double _2, U32 _3);
typedef float  (STDCALL *_fCffuf)(float _0, float _1, U32 _2, float _3);
typedef float  (STDCALL *_fCffud)(float _0, float _1, U32 _2, double _3);
typedef float  (STDCALL *_fCffuu)(float _0, float _1, U32 _2, U32 _3);
typedef float  (STDCALL *_fCfdff)(float _0, double _1, float _2, float _3);
typedef float  (STDCALL *_fCfdfd)(float _0, double _1, float _2, double _3);
typedef float  (STDCALL *_fCfdfu)(float _0, double _1, float _2, U32 _3);
typedef float  (STDCALL *_fCfddf)(float _0, double _1, double _2, float _3);
typedef float  (STDCALL *_fCfddd)(float _0, double _1, double _2, double _3);
typedef float  (STDCALL *_fCfddu)(float _0, double _1, double _2, U32 _3);
typedef float  (STDCALL *_fCfduf)(float _0, double _1, U32 _2, float _3);
typedef float  (STDCALL *_fCfdud)(float _0, double _1, U32 _2, double _3);
typedef float  (STDCALL *_fCfduu)(float _0, double _1, U32 _2, U32 _3);
typedef float  (STDCALL *_fCfuff)(float _0, U32 _1, float _2, float _3);
typedef float  (STDCALL *_fCfufd)(float _0, U32 _1, float _2, double _3);
typedef float  (STDCALL *_fCfufu)(float _0, U32 _1, float _2, U32 _3);
typedef float  (STDCALL *_fCfudf)(float _0, U32 _1, double _2, float _3);
typedef float  (STDCALL *_fCfudd)(float _0, U32 _1, double _2, double _3);
typedef float  (STDCALL *_fCfudu)(float _0, U32 _1, double _2, U32 _3);
typedef float  (STDCALL *_fCfuuf)(float _0, U32 _1, U32 _2, float _3);
typedef float  (STDCALL *_fCfuud)(float _0, U32 _1, U32 _2, double _3);
typedef float  (STDCALL *_fCfuuu)(float _0, U32 _1, U32 _2, U32 _3);
typedef float  (STDCALL *_fCdfff)(double _0, float _1, float _2, float _3);
typedef float  (STDCALL *_fCdffd)(double _0, float _1, float _2, double _3);
typedef float  (STDCALL *_fCdffu)(double _0, float _1, float _2, U32 _3);
typedef float  (STDCALL *_fCdfdf)(double _0, float _1, double _2, float _3);
typedef float  (STDCALL *_fCdfdd)(double _0, float _1, double _2, double _3);
typedef float  (STDCALL *_fCdfdu)(double _0, float _1, double _2, U32 _3);
typedef float  (STDCALL *_fCdfuf)(double _0, float _1, U32 _2, float _3);
typedef float  (STDCALL *_fCdfud)(double _0, float _1, U32 _2, double _3);
typedef float  (STDCALL *_fCdfuu)(double _0, float _1, U32 _2, U32 _3);
typedef float  (STDCALL *_fCddff)(double _0, double _1, float _2, float _3);
typedef float  (STDCALL *_fCddfd)(double _0, double _1, float _2, double _3);
typedef float  (STDCALL *_fCddfu)(double _0, double _1, float _2, U32 _3);
typedef float  (STDCALL *_fCdddf)(double _0, double _1, double _2, float _3);
typedef float  (STDCALL *_fCdddd)(double _0, double _1, double _2, double _3);
typedef float  (STDCALL *_fCdddu)(double _0, double _1, double _2, U32 _3);
typedef float  (STDCALL *_fCdduf)(double _0, double _1, U32 _2, float _3);
typedef float  (STDCALL *_fCddud)(double _0, double _1, U32 _2, double _3);
typedef float  (STDCALL *_fCdduu)(double _0, double _1, U32 _2, U32 _3);
typedef float  (STDCALL *_fCduff)(double _0, U32 _1, float _2, float _3);
typedef float  (STDCALL *_fCdufd)(double _0, U32 _1, float _2, double _3);
typedef float  (STDCALL *_fCdufu)(double _0, U32 _1, float _2, U32 _3);
typedef float  (STDCALL *_fCdudf)(double _0, U32 _1, double _2, float _3);
typedef float  (STDCALL *_fCdudd)(double _0, U32 _1, double _2, double _3);
typedef float  (STDCALL *_fCdudu)(double _0, U32 _1, double _2, U32 _3);
typedef float  (STDCALL *_fCduuf)(double _0, U32 _1, U32 _2, float _3);
typedef float  (STDCALL *_fCduud)(double _0, U32 _1, U32 _2, double _3);
typedef float  (STDCALL *_fCduuu)(double _0, U32 _1, U32 _2, U32 _3);
typedef float  (STDCALL *_fCufff)(U32 _0, float _1, float _2, float _3);
typedef float  (STDCALL *_fCuffd)(U32 _0, float _1, float _2, double _3);
typedef float  (STDCALL *_fCuffu)(U32 _0, float _1, float _2, U32 _3);
typedef float  (STDCALL *_fCufdf)(U32 _0, float _1, double _2, float _3);
typedef float  (STDCALL *_fCufdd)(U32 _0, float _1, double _2, double _3);
typedef float  (STDCALL *_fCufdu)(U32 _0, float _1, double _2, U32 _3);
typedef float  (STDCALL *_fCufuf)(U32 _0, float _1, U32 _2, float _3);
typedef float  (STDCALL *_fCufud)(U32 _0, float _1, U32 _2, double _3);
typedef float  (STDCALL *_fCufuu)(U32 _0, float _1, U32 _2, U32 _3);
typedef float  (STDCALL *_fCudff)(U32 _0, double _1, float _2, float _3);
typedef float  (STDCALL *_fCudfd)(U32 _0, double _1, float _2, double _3);
typedef float  (STDCALL *_fCudfu)(U32 _0, double _1, float _2, U32 _3);
typedef float  (STDCALL *_fCuddf)(U32 _0, double _1, double _2, float _3);
typedef float  (STDCALL *_fCuddd)(U32 _0, double _1, double _2, double _3);
typedef float  (STDCALL *_fCuddu)(U32 _0, double _1, double _2, U32 _3);
typedef float  (STDCALL *_fCuduf)(U32 _0, double _1, U32 _2, float _3);
typedef float  (STDCALL *_fCudud)(U32 _0, double _1, U32 _2, double _3);
typedef float  (STDCALL *_fCuduu)(U32 _0, double _1, U32 _2, U32 _3);
typedef float  (STDCALL *_fCuuff)(U32 _0, U32 _1, float _2, float _3);
typedef float  (STDCALL *_fCuufd)(U32 _0, U32 _1, float _2, double _3);
typedef float  (STDCALL *_fCuufu)(U32 _0, U32 _1, float _2, U32 _3);
typedef float  (STDCALL *_fCuudf)(U32 _0, U32 _1, double _2, float _3);
typedef float  (STDCALL *_fCuudd)(U32 _0, U32 _1, double _2, double _3);
typedef float  (STDCALL *_fCuudu)(U32 _0, U32 _1, double _2, U32 _3);
typedef float  (STDCALL *_fCuuuf)(U32 _0, U32 _1, U32 _2, float _3);
typedef float  (STDCALL *_fCuuud)(U32 _0, U32 _1, U32 _2, double _3);
typedef float  (STDCALL *_fCuuuu)(U32 _0, U32 _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCffff)(float _0, float _1, float _2, float _3);
typedef double (STDCALL *_dCfffd)(float _0, float _1, float _2, double _3);
typedef double (STDCALL *_dCfffu)(float _0, float _1, float _2, U32 _3);
typedef double (STDCALL *_dCffdf)(float _0, float _1, double _2, float _3);
typedef double (STDCALL *_dCffdd)(float _0, float _1, double _2, double _3);
typedef double (STDCALL *_dCffdu)(float _0, float _1, double _2, U32 _3);
typedef double (STDCALL *_dCffuf)(float _0, float _1, U32 _2, float _3);
typedef double (STDCALL *_dCffud)(float _0, float _1, U32 _2, double _3);
typedef double (STDCALL *_dCffuu)(float _0, float _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCfdff)(float _0, double _1, float _2, float _3);
typedef double (STDCALL *_dCfdfd)(float _0, double _1, float _2, double _3);
typedef double (STDCALL *_dCfdfu)(float _0, double _1, float _2, U32 _3);
typedef double (STDCALL *_dCfddf)(float _0, double _1, double _2, float _3);
typedef double (STDCALL *_dCfddd)(float _0, double _1, double _2, double _3);
typedef double (STDCALL *_dCfddu)(float _0, double _1, double _2, U32 _3);
typedef double (STDCALL *_dCfduf)(float _0, double _1, U32 _2, float _3);
typedef double (STDCALL *_dCfdud)(float _0, double _1, U32 _2, double _3);
typedef double (STDCALL *_dCfduu)(float _0, double _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCfuff)(float _0, U32 _1, float _2, float _3);
typedef double (STDCALL *_dCfufd)(float _0, U32 _1, float _2, double _3);
typedef double (STDCALL *_dCfufu)(float _0, U32 _1, float _2, U32 _3);
typedef double (STDCALL *_dCfudf)(float _0, U32 _1, double _2, float _3);
typedef double (STDCALL *_dCfudd)(float _0, U32 _1, double _2, double _3);
typedef double (STDCALL *_dCfudu)(float _0, U32 _1, double _2, U32 _3);
typedef double (STDCALL *_dCfuuf)(float _0, U32 _1, U32 _2, float _3);
typedef double (STDCALL *_dCfuud)(float _0, U32 _1, U32 _2, double _3);
typedef double (STDCALL *_dCfuuu)(float _0, U32 _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCdfff)(double _0, float _1, float _2, float _3);
typedef double (STDCALL *_dCdffd)(double _0, float _1, float _2, double _3);
typedef double (STDCALL *_dCdffu)(double _0, float _1, float _2, U32 _3);
typedef double (STDCALL *_dCdfdf)(double _0, float _1, double _2, float _3);
typedef double (STDCALL *_dCdfdd)(double _0, float _1, double _2, double _3);
typedef double (STDCALL *_dCdfdu)(double _0, float _1, double _2, U32 _3);
typedef double (STDCALL *_dCdfuf)(double _0, float _1, U32 _2, float _3);
typedef double (STDCALL *_dCdfud)(double _0, float _1, U32 _2, double _3);
typedef double (STDCALL *_dCdfuu)(double _0, float _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCddff)(double _0, double _1, float _2, float _3);
typedef double (STDCALL *_dCddfd)(double _0, double _1, float _2, double _3);
typedef double (STDCALL *_dCddfu)(double _0, double _1, float _2, U32 _3);
typedef double (STDCALL *_dCdddf)(double _0, double _1, double _2, float _3);
typedef double (STDCALL *_dCdddd)(double _0, double _1, double _2, double _3);
typedef double (STDCALL *_dCdddu)(double _0, double _1, double _2, U32 _3);
typedef double (STDCALL *_dCdduf)(double _0, double _1, U32 _2, float _3);
typedef double (STDCALL *_dCddud)(double _0, double _1, U32 _2, double _3);
typedef double (STDCALL *_dCdduu)(double _0, double _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCduff)(double _0, U32 _1, float _2, float _3);
typedef double (STDCALL *_dCdufd)(double _0, U32 _1, float _2, double _3);
typedef double (STDCALL *_dCdufu)(double _0, U32 _1, float _2, U32 _3);
typedef double (STDCALL *_dCdudf)(double _0, U32 _1, double _2, float _3);
typedef double (STDCALL *_dCdudd)(double _0, U32 _1, double _2, double _3);
typedef double (STDCALL *_dCdudu)(double _0, U32 _1, double _2, U32 _3);
typedef double (STDCALL *_dCduuf)(double _0, U32 _1, U32 _2, float _3);
typedef double (STDCALL *_dCduud)(double _0, U32 _1, U32 _2, double _3);
typedef double (STDCALL *_dCduuu)(double _0, U32 _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCufff)(U32 _0, float _1, float _2, float _3);
typedef double (STDCALL *_dCuffd)(U32 _0, float _1, float _2, double _3);
typedef double (STDCALL *_dCuffu)(U32 _0, float _1, float _2, U32 _3);
typedef double (STDCALL *_dCufdf)(U32 _0, float _1, double _2, float _3);
typedef double (STDCALL *_dCufdd)(U32 _0, float _1, double _2, double _3);
typedef double (STDCALL *_dCufdu)(U32 _0, float _1, double _2, U32 _3);
typedef double (STDCALL *_dCufuf)(U32 _0, float _1, U32 _2, float _3);
typedef double (STDCALL *_dCufud)(U32 _0, float _1, U32 _2, double _3);
typedef double (STDCALL *_dCufuu)(U32 _0, float _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCudff)(U32 _0, double _1, float _2, float _3);
typedef double (STDCALL *_dCudfd)(U32 _0, double _1, float _2, double _3);
typedef double (STDCALL *_dCudfu)(U32 _0, double _1, float _2, U32 _3);
typedef double (STDCALL *_dCuddf)(U32 _0, double _1, double _2, float _3);
typedef double (STDCALL *_dCuddd)(U32 _0, double _1, double _2, double _3);
typedef double (STDCALL *_dCuddu)(U32 _0, double _1, double _2, U32 _3);
typedef double (STDCALL *_dCuduf)(U32 _0, double _1, U32 _2, float _3);
typedef double (STDCALL *_dCudud)(U32 _0, double _1, U32 _2, double _3);
typedef double (STDCALL *_dCuduu)(U32 _0, double _1, U32 _2, U32 _3);
typedef double (STDCALL *_dCuuff)(U32 _0, U32 _1, float _2, float _3);
typedef double (STDCALL *_dCuufd)(U32 _0, U32 _1, float _2, double _3);
typedef double (STDCALL *_dCuufu)(U32 _0, U32 _1, float _2, U32 _3);
typedef double (STDCALL *_dCuudf)(U32 _0, U32 _1, double _2, float _3);
typedef double (STDCALL *_dCuudd)(U32 _0, U32 _1, double _2, double _3);
typedef double (STDCALL *_dCuudu)(U32 _0, U32 _1, double _2, U32 _3);
typedef double (STDCALL *_dCuuuf)(U32 _0, U32 _1, U32 _2, float _3);
typedef double (STDCALL *_dCuuud)(U32 _0, U32 _1, U32 _2, double _3);
typedef double (STDCALL *_dCuuuu)(U32 _0, U32 _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCffff)(float _0, float _1, float _2, float _3);
typedef U64    (STDCALL *_uCfffd)(float _0, float _1, float _2, double _3);
typedef U64    (STDCALL *_uCfffu)(float _0, float _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCffdf)(float _0, float _1, double _2, float _3);
typedef U64    (STDCALL *_uCffdd)(float _0, float _1, double _2, double _3);
typedef U64    (STDCALL *_uCffdu)(float _0, float _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCffuf)(float _0, float _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCffud)(float _0, float _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCffuu)(float _0, float _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCfdff)(float _0, double _1, float _2, float _3);
typedef U64    (STDCALL *_uCfdfd)(float _0, double _1, float _2, double _3);
typedef U64    (STDCALL *_uCfdfu)(float _0, double _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCfddf)(float _0, double _1, double _2, float _3);
typedef U64    (STDCALL *_uCfddd)(float _0, double _1, double _2, double _3);
typedef U64    (STDCALL *_uCfddu)(float _0, double _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCfduf)(float _0, double _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCfdud)(float _0, double _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCfduu)(float _0, double _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCfuff)(float _0, U32 _1, float _2, float _3);
typedef U64    (STDCALL *_uCfufd)(float _0, U32 _1, float _2, double _3);
typedef U64    (STDCALL *_uCfufu)(float _0, U32 _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCfudf)(float _0, U32 _1, double _2, float _3);
typedef U64    (STDCALL *_uCfudd)(float _0, U32 _1, double _2, double _3);
typedef U64    (STDCALL *_uCfudu)(float _0, U32 _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCfuuf)(float _0, U32 _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCfuud)(float _0, U32 _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCfuuu)(float _0, U32 _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCdfff)(double _0, float _1, float _2, float _3);
typedef U64    (STDCALL *_uCdffd)(double _0, float _1, float _2, double _3);
typedef U64    (STDCALL *_uCdffu)(double _0, float _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCdfdf)(double _0, float _1, double _2, float _3);
typedef U64    (STDCALL *_uCdfdd)(double _0, float _1, double _2, double _3);
typedef U64    (STDCALL *_uCdfdu)(double _0, float _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCdfuf)(double _0, float _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCdfud)(double _0, float _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCdfuu)(double _0, float _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCddff)(double _0, double _1, float _2, float _3);
typedef U64    (STDCALL *_uCddfd)(double _0, double _1, float _2, double _3);
typedef U64    (STDCALL *_uCddfu)(double _0, double _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCdddf)(double _0, double _1, double _2, float _3);
typedef U64    (STDCALL *_uCdddd)(double _0, double _1, double _2, double _3);
typedef U64    (STDCALL *_uCdddu)(double _0, double _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCdduf)(double _0, double _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCddud)(double _0, double _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCdduu)(double _0, double _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCduff)(double _0, U32 _1, float _2, float _3);
typedef U64    (STDCALL *_uCdufd)(double _0, U32 _1, float _2, double _3);
typedef U64    (STDCALL *_uCdufu)(double _0, U32 _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCdudf)(double _0, U32 _1, double _2, float _3);
typedef U64    (STDCALL *_uCdudd)(double _0, U32 _1, double _2, double _3);
typedef U64    (STDCALL *_uCdudu)(double _0, U32 _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCduuf)(double _0, U32 _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCduud)(double _0, U32 _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCduuu)(double _0, U32 _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCufff)(U32 _0, float _1, float _2, float _3);
typedef U64    (STDCALL *_uCuffd)(U32 _0, float _1, float _2, double _3);
typedef U64    (STDCALL *_uCuffu)(U32 _0, float _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCufdf)(U32 _0, float _1, double _2, float _3);
typedef U64    (STDCALL *_uCufdd)(U32 _0, float _1, double _2, double _3);
typedef U64    (STDCALL *_uCufdu)(U32 _0, float _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCufuf)(U32 _0, float _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCufud)(U32 _0, float _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCufuu)(U32 _0, float _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCudff)(U32 _0, double _1, float _2, float _3);
typedef U64    (STDCALL *_uCudfd)(U32 _0, double _1, float _2, double _3);
typedef U64    (STDCALL *_uCudfu)(U32 _0, double _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCuddf)(U32 _0, double _1, double _2, float _3);
typedef U64    (STDCALL *_uCuddd)(U32 _0, double _1, double _2, double _3);
typedef U64    (STDCALL *_uCuddu)(U32 _0, double _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCuduf)(U32 _0, double _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCudud)(U32 _0, double _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCuduu)(U32 _0, double _1, U32 _2, U32 _3);
typedef U64    (STDCALL *_uCuuff)(U32 _0, U32 _1, float _2, float _3);
typedef U64    (STDCALL *_uCuufd)(U32 _0, U32 _1, float _2, double _3);
typedef U64    (STDCALL *_uCuufu)(U32 _0, U32 _1, float _2, U32 _3);
typedef U64    (STDCALL *_uCuudf)(U32 _0, U32 _1, double _2, float _3);
typedef U64    (STDCALL *_uCuudd)(U32 _0, U32 _1, double _2, double _3);
typedef U64    (STDCALL *_uCuudu)(U32 _0, U32 _1, double _2, U32 _3);
typedef U64    (STDCALL *_uCuuuf)(U32 _0, U32 _1, U32 _2, float _3);
typedef U64    (STDCALL *_uCuuud)(U32 _0, U32 _1, U32 _2, double _3);
typedef U64    (STDCALL *_uCuuuu)(U32 _0, U32 _1, U32 _2, U32 _3);
